//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp7.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> ItemParametr2 { get; set; }
        public string ItemParametr3 { get; set; }
        public string ItemParametr4 { get; set; }
        public string ItemParametr5 { get; set; }
    
        public virtual ItemCategory ItemCategory { get; set; }
    }
}
